config_version = 14

[bar.default]
center = [ "clock", "control-center", "theme_mode" ]
end = [
    "media",
    "tray",
    "notifications",
    "screenshot",
    "clipboard",
    "network",
    "bluetooth",
    "volume",
    "brightness",
    "battery",
    "session"
]

[battery]
warning_threshold = 15

[brightness]
enable_ddcutil = true

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 300.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 450.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 330.0

[lockscreen]
fingerprint = false

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-1", "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 1280.0
    cy = 1258.0
    output = "HDMI-A-1"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[[plugins.source]]
enabled = false
kind = "git"
location = "https://github.com/noctalia-dev/official-plugins"
name = "official"

[[plugins.source]]
enabled = false
kind = "git"
location = "https://github.com/noctalia-dev/community-plugins"
name = "community"

[shell]
offline_mode = true
polkit_agent = true

    [shell.screenshot]
    annotate = true
    confirm_region = true
    directory = "~/Pictures/Screenshots"

[system.monitor]
enabled = false

[theme]
builtin = "Dracula"
mode = "dark"

[wallpaper]
directory = "~/Pictures/Wallpapers"

[weather]
enabled = false

[widget.bluetooth]
show_label = true

[widget.brightness]
show_label = false

[widget.media]
enabled = false

[widget.volume]
show_label = false
