# Font and window comfort
font_size 12.0
disable_ligatures cursor
window_padding_width 6
# cursor_trail 3
enable_audio_bell no

# Scrollback and copied text
scrollback_lines 10000
scrollback_pager_history_size 10
strip_trailing_spaces smart

# BEGIN_KITTY_THEME
# Tokyo Night
include current-theme.conf
# END_KITTY_THEME
